image: docker:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_VERSION: 0.69.0

services:
  - docker:dind

stages:
 - build
 - deploy

build:
  stage: build
  script:
    - apk add git
    - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
    - tar -xvzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -C /bin hugo
    - hugo
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master