image: docker:latest


variables:
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - docker:dind


before_script:
  - apk add git
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
  - tar -xvzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -C /bin hugo

stages:
 - test
 - pages

test:
    stage: test
    script:
    - hugo
    except:
    - master

pages:
    stage: pages
    script:
    - hugo
    - docker build . -t $CI_REGISTRY/$GROUP/$PROJECT
    - docker push $CI_REGISTRY/$GROUP/$PROJECT
    artifacts:
        paths:
        - public
    only:
    - master