baseURL = "https://hackerspaceszeged.gitlab.io/"
languageCode = "hu-hu"
title = "HackerSpace Szeged"
theme = "terminal"
DefaultContentLanguage = "hu"
buildFuture = true
enableGitInfo = true

[params]
themeColor = "blue"
fullWidthTheme = false
centerTheme = true
HackSenseEnable = true
HackSenseURL = "https://api.hackerspace-szeged.hu"
showGenerationTime = false
showGitVersion = true

[languages]
  [languages.hu]
    title = "HackerSpace Szeged"
    subtitle = ""
    keywords = ""
    copyright = "© 2015-2019 Hackerspace Szeged"
    menuMore = "Többi menüpont"
    readMore = "Tovább"
    readOtherPosts = "Többi bejegyzés"

    [languages.hu.params.logo]
      logoText = "Hackerpace Szeged"
      logoHomeLink = "/"

    [languages.hu.menu]
      [[languages.hu.menu.main]]
        identifier = "main"
        name = "Kezdőlap"
        url = "/"
        weight = 1
      [[languages.hu.menu.main]]
        identifier = "events"
        name = "Események"
        url = "/events"
        weight = 3
      [[languages.hu.menu.main]]
        identifier = "projects"
        name = "Projektek"
        url = "/projects"
        weight = 4
      [[languages.hu.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
        weight = 5
      [[languages.hu.menu.main]]
        identifier = "contact"
        name = "Kapcsolat"
        url = "/contact"
        weight = 6
