baseURL = "https://szeged.hacker-space.hu/"
languageCode = "hu-hu"
title = "Hackerspace Szeged"
theme = "terminal"
DefaultContentLanguage = "hu"
buildFuture = true

[params]
themeColor = "blue"
fullWidthTheme = false
centerTheme = true
HackSenseEnable = false
HackSenseURL = "https://api.szeged.hacker-space.hu/"
showGenerationTime = false
showGitVersion = true

[security]
  [security.funcs]
    getenv = ['COMMIT_SHA']

[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.hu]
    title = "Hackerspace Szeged"
    subtitle = ""
    keywords = ""
    copyright = "© 2015-2022 Hackerspace Szeged"
    menuMore = "Többi menüpont"
    readMore = "Tovább"
    readOtherPosts = "Többi bejegyzés"

    [languages.hu.params.logo]
      logoText = "Hackerspace Szeged"
      logoHomeLink = "/"

    [languages.hu.menu]
      [[languages.hu.menu.main]]
        identifier = "main"
        name = "Kezdőlap"
        url = "/"
        weight = 1
      [[languages.hu.menu.main]]
        identifier = "events"
        name = "Események"
        url = "/events"
        weight = 3
      [[languages.hu.menu.main]]
        identifier = "projects"
        name = "Projektek"
        url = "/projects"
        weight = 4
      [[languages.hu.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
        weight = 5
      [[languages.hu.menu.main]]
        identifier = "contact"
        name = "Kapcsolat"
        url = "/contact"
        weight = 6
