baseURL = "https://hs.atch.xyz/"
languageCode = "hu-hu"
title = "Hackerspace Szeged"
theme = "terminal"
DefaultContentLanguage = "hu"

[params]
themeColor = "blue"
fullWidthTheme = false
centerTheme = true
HackSenseEnable = true
HackSenseURL = "https://hsapi.atch.xyz"
showGenerationTime = false

[languages]
  [languages.hu]
    title = "Hackerspace Szeged"
    subtitle = ""
    keywords = ""
    copyright = "© 2015-2019 Hackerspace Szeged"
    menuMore = "Többi menüpont"
    readMore = "Tovább"
    readOtherPosts = "Többi bejegyzés"

    [languages.hu.params.logo]
      logoText = "HackerspaceSzeged"
      logoHomeLink = "/"

    [languages.hu.menu]
      [[languages.hu.menu.main]]
        identifier = "events"
        name = "Események"
        url = "/events"
        weight = 1
      [[languages.hu.menu.main]]
        identifier = "projects"
        name = "Projektek"
        url = "/projects"
        weight = 2
      [[languages.hu.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
        weight = 3
      [[languages.hu.menu.main]]
        identifier = "contact"
        name = "Kapcsolat"
        url = "/contact"
        weight = 4
